### ISSUE TITLE
Issue when running in an alpine docker container

### ISSUE THREAD

**Issue by dnesbitt03qub** [b1f6c1c4/draw.io-export#1]
I've been attempting to get this running in an alpine docker container and I'm getting occasional errors, it doesn't happen every time the tool is run.

```
Error: Evaluation failed: ReferenceError: Graph is not defined
    at render (https://www.draw.io/export3.html:36:16)
    at __puppeteer_evaluation_script__:1:11
    at ExecutionContext.evaluateHandle (/home/.npm-global/lib/node_modules/puppeteer/lib/ExecutionContext.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm using a patch to get puppeteer running on the base alpine image by getting chromium from apk and using puppeteer 1.8.0.

```
@@ -54,6 +54,8 @@
 
   const browser = await puppeteer.launch({
     headless: true,
+    executablePath: '/usr/bin/chromium-browser',
+    args: ['--no-sandbox', '--disable-dev-shm-usage'],
   });
```

Is this a draw.io-export issue or a puppeteer one?

**Comment by b1f6c1c4** [comment]
I think it's `puppeteer`'s problem. See https://github.com/GoogleChrome/puppeteer/issues/379

BTW, I developed `draw.io-export` mostly for the purpose of local-install and generate `pdf` from `xml`, see https://github.com/b1f6c1c4/ansys-moe/blob/thesis/Makefile#L23
So I have no idea if it'll work in docker

Feel free to extend more functionality and use case for `draw.io-export`!

**Comment by b1f6c1c4** [comment]
I cloned my repo, applied your patch, and tried the following Dockerfile:

```Dockerfile
FROM alpine
RUN apk add nodejs yarn chromium
WORKDIR /root
COPY package.json yarn.lock ./
RUN yarn
COPY . .
```

It works like charm...

Potential problem:
* Try bump math jax version https://github.com/b1f6c1c4/draw.io-export/commit/22ae399566cb970a8bee4e7998c750c501d2b115
* Try simpler draw.io files first

**Comment by dnesbitt03qub** [comment]
Cloned the git (with commit 22ae399) and ran with that Dockerfile, works perfectly! Thanks!
