### ISSUE TITLE
the format flag got included in the output filename

### ISSUE THREAD

**Issue by bhomass** [b1f6c1c4/draw.io-export#25]
i ran drawio against a pretty large drawio file. there isn't a clear instruction how to separate the format flag from the output filename.

what I did was 
drawio input.drawio -o output.split-id-png.diagrm.png

it correctly output a single png per tab in the draw.io file. even included the tab name in the output file. like
output.split-id-pngApplication_Architecture.png

I really like the fact it captured the tab name "Application_Architecture", but I don't want the inclusion of ".split-id-png' everywhere. I can not simply skip split-id-png, because that tell the program to generate the multiple PNG files. 

is there a right way to make this call?

**Comment by b1f6c1c4** [comment]
Apologize for the poor documentation, the command line would be:

`drawio <input> -F split-id-png -o <output>`

**Comment by bhomass** [comment]
so I tried
drawio input.drawio -F split-id-png -o diagrm.png

now I get diagrm.pngApplication_Architecture.png

if drawio input.drawio -F split-id-png -o png
I get
pngApplication_Architecture.png

if if drawio input.drawio -F split-id-png
I get 
a.pngApplication_Architecture.png

How can get just Application_Architecture.png?

**Comment by b1f6c1c4** [comment]
Try `drawio input.drawio -F split-id-png -o ''` or `drawio input.drawio -F split-id-png -o ./`

The program is using plain text concatenation for output file naming, so giving it an empty (or effectively empty) string would suffice.

**Comment by bhomass** [comment]
Thank you. drawio DAS_iPlus_DrawIO.drawio -F split-id-png -o ./ worked.

drawio input.drawio -F split-id-png -o '' did not work, it seems to add some invisible space before the filename.
