### ISSUE TITLE
Do the PNGs contain the XML?

### ISSUE THREAD

**Issue by CholoTook** [b1f6c1c4/draw.io-export#7]
Hi,

When I save via draw.io, I can choose weather or not to save the XML inside the PNG.

Is there an option to do that?

Many thanks,
DAn.

**Comment by b1f6c1c4** [comment]
Unfortunately my `draw.io-export` does not support this feature. I've found some alternatives for you in case you are interested:
(I've never tried them, use at your own risk)

- https://github.com/jgraph/draw-image-export2#common-parameters
- https://github.com/jgraph/docker-drawio (which uses the above repo internally)
- https://github.com/jgraph/drawio-desktop

Alternatively, you may want to incorporate [the code that produces embedded xml in PNG](https://github.com/jgraph/draw-image-export2/blob/master/export.js#L596-L600) into [this repo](https://github.com/b1f6c1c4/draw.io-export/blob/master/export.js#L111-L116) and submit a PR.

**Comment by CholoTook** [comment]
Many thanks b1f6c1c4!
